# Generated by Django 3.0.7 on 2020-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_addition_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition_info',
            name='slug',
            field=models.SlugField(default='item'),
        ),
    ]
