# Generated by Django 3.0.7 on 2020-09-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_addition_info_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition_info',
            old_name='description',
            new_name='descriptions',
        ),
    ]
