# Generated by Django 3.0.7 on 2020-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200930_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Electronics', 'Electronics'), ('Cars', 'Cars'), ('Food', 'Food'), ('Books', 'Books'), ('Shoe', 'Shoe')], default='Food', max_length=15),
        ),
    ]
