# Generated by Django 3.0.7 on 2020-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition_info',
            name='slug',
            field=models.SlugField(default='Food'),
        ),
    ]
