# Generated by Django 3.0.7 on 2020-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200930_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about')),
                ('title1', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('title2', models.CharField(max_length=200)),
                ('description2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about')),
            ],
        ),
    ]
